// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx5f7nMKs4hazOnQHgUfjCYb4fP1-ghcI',
    appId: '1:381219936756:web:872f980db0e579d3afc1a1',
    messagingSenderId: '381219936756',
    projectId: 'pushnotification-19171',
    authDomain: 'pushnotification-19171.firebaseapp.com',
    storageBucket: 'pushnotification-19171.appspot.com',
    measurementId: 'G-EN1WQEM8SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN4wpccuGgD4myWdsEkMq0MsgY-Z2De2A',
    appId: '1:381219936756:android:7466e15909d30de8afc1a1',
    messagingSenderId: '381219936756',
    projectId: 'pushnotification-19171',
    storageBucket: 'pushnotification-19171.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwUGzKdDPD8yP1GXac5aA1CQo2J0zWHqU',
    appId: '1:381219936756:ios:9cfa408cda2cdd53afc1a1',
    messagingSenderId: '381219936756',
    projectId: 'pushnotification-19171',
    storageBucket: 'pushnotification-19171.appspot.com',
    androidClientId: '381219936756-osidjpd8ntkto8la6juje3qboj7vtrem.apps.googleusercontent.com',
    iosClientId: '381219936756-52tkeou2074rp6kqj0ho7piaceakag9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwUGzKdDPD8yP1GXac5aA1CQo2J0zWHqU',
    appId: '1:381219936756:ios:9cfa408cda2cdd53afc1a1',
    messagingSenderId: '381219936756',
    projectId: 'pushnotification-19171',
    storageBucket: 'pushnotification-19171.appspot.com',
    androidClientId: '381219936756-osidjpd8ntkto8la6juje3qboj7vtrem.apps.googleusercontent.com',
    iosClientId: '381219936756-52tkeou2074rp6kqj0ho7piaceakag9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTest',
  );
}
